# read()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_read.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/read.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# write()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_write.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/write.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# ioctl()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_ioctl.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/ioctl.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# futex()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_futex.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/futex.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# epoll_pwait()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_epoll_pwait.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/epoll_pwait.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# clock_gettime()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_clock_gettime.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/clock_gettime.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# gettimeofday()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_gettimeofday.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/gettimeofday.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# getuid32()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_getuid32.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/getuid32.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# mmap2()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_mmap2.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/mmap2.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# mprotect()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_mprotect.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/mprotect.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()

# prctl()
mydatat <- read.delim("/home/mac/git/energy/android/data/syscall_prctl.txt", sep = "\n", dec = ",", skip = 7)
png(filename = "/home/mac/git/energy/android/data/plot/prctl.png", width = 8600, height = 1000)
plot(c(1:length(unlist(mydatat))), as.numeric(unlist(mydatat)), type="l", xlab = "Sample", ylab = "Current (A)")
dev.off()